# Generated by Django 4.2.27 on 2026-02-01 13:55

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('info_id', models.AutoField(primary_key=True, serialize=False)),
                ('intro', models.TextField()),
                ('address', models.TextField()),
                ('facebook_url', models.URLField(blank=True, max_length=255, null=True)),
                ('email_add', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'personal_information',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('proj_id', models.AutoField(primary_key=True, serialize=False)),
                ('proj_name', models.CharField(max_length=100, verbose_name='Name')),
                ('proj_desc', models.TextField(verbose_name='Description')),
                ('proj_url', models.URLField(blank=True, max_length=255, null=True)),
                ('proj_languages', models.JSONField(blank=True, null=True)),
                ('proj_image', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='projects-img/')),
                ('proj_pdf', models.FileField(upload_to='projects-pdfs/')),
                ('year', models.CharField(max_length=4, verbose_name='Year')),
            ],
            options={
                'db_table': 'projects',
            },
        ),
    ]
