# Generated by Django 4.2.27 on 2026-02-04 05:59

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio2025', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=80, scale=None, size=[1920, 1080], upload_to='tech-icons/')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('exp_id', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.CharField(max_length=100, verbose_name='Name')),
                ('exp_desc', models.TextField(verbose_name='Description')),
                ('date_serve', models.TextField(verbose_name='Employment Period')),
                ('location', models.CharField(max_length=100, verbose_name='Name')),
                ('tech_used', models.ManyToManyField(blank=True, related_name='experiences', to='portfolio2025.technology')),
            ],
            options={
                'db_table': 'experiences',
            },
        ),
    ]
