# Generated by Django 4.2.27 on 2026-02-04 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio2025', '0002_technology_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='location',
            field=models.CharField(max_length=100, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='information',
            name='facebook_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
